// This file is @generated by prost-build.
/// A usage event representing a billable action.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsageEvent {
    /// Unique transaction ID for idempotency (required).
    #[prost(string, tag = "1")]
    pub transaction_id: ::prost::alloc::string::String,
    /// Organization UUID (required).
    #[prost(string, tag = "2")]
    pub organization_id: ::prost::alloc::string::String,
    /// Agent UUID (required).
    #[prost(string, tag = "3")]
    pub agent_id: ::prost::alloc::string::String,
    /// External subscription ID for billing integration (optional).
    #[prost(string, tag = "4")]
    pub external_subscription_id: ::prost::alloc::string::String,
    /// Event type code.
    #[prost(enumeration = "UsageEventType", tag = "5")]
    pub event_type: i32,
    /// Billable metric code (e.g., "api_calls").
    #[prost(string, tag = "6")]
    pub code: ::prost::alloc::string::String,
    /// Quantity of the billable unit (must be positive).
    #[prost(int64, tag = "7")]
    pub quantity: i64,
    /// When the event occurred.
    #[prost(message, optional, tag = "8")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Additional properties for filtering.
    #[prost(message, optional, tag = "9")]
    pub properties: ::core::option::Option<::prost_types::Struct>,
    /// Delegation depth when event was generated.
    #[prost(uint32, tag = "10")]
    pub delegation_depth: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestEventRequest {
    #[prost(message, optional, tag = "1")]
    pub event: ::core::option::Option<UsageEvent>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestEventResponse {
    /// Whether the event was successfully ingested.
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Status of the ingestion.
    #[prost(enumeration = "IngestStatus", tag = "2")]
    pub status: i32,
    /// Error message if not successful.
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestEventBatchRequest {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<UsageEvent>,
    /// If true, continue processing remaining events on individual failures.
    #[prost(bool, tag = "2")]
    pub continue_on_error: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestEventBatchResponse {
    /// Number of events successfully ingested.
    #[prost(int32, tag = "1")]
    pub accepted_count: i32,
    /// Number of duplicate events skipped.
    #[prost(int32, tag = "2")]
    pub duplicate_count: i32,
    /// Number of events that failed validation.
    #[prost(int32, tag = "3")]
    pub failed_count: i32,
    /// Per-event results (only included if there were failures).
    #[prost(message, repeated, tag = "4")]
    pub results: ::prost::alloc::vec::Vec<EventResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventResult {
    /// Index of the event in the batch.
    #[prost(int32, tag = "1")]
    pub index: i32,
    /// Status of this specific event.
    #[prost(enumeration = "IngestStatus", tag = "2")]
    pub status: i32,
    /// Error message if failed.
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckQuotaRequest {
    /// Organization UUID.
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Agent UUID (optional, for agent-specific quotas).
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    /// Metric code to check.
    #[prost(string, tag = "3")]
    pub metric_code: ::prost::alloc::string::String,
    /// Requested quantity.
    #[prost(int64, tag = "4")]
    pub quantity: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckQuotaResponse {
    /// Whether the usage is allowed.
    #[prost(bool, tag = "1")]
    pub allowed: bool,
    /// Current usage in the period.
    #[prost(int64, tag = "2")]
    pub current_usage: i64,
    /// Limit for the period.
    #[prost(int64, tag = "3")]
    pub limit: i64,
    /// Remaining quota.
    #[prost(int64, tag = "4")]
    pub remaining: i64,
    /// If not allowed, reason why.
    #[prost(string, tag = "5")]
    pub denial_reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetQuotaStatusRequest {
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub metric_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetQuotaStatusResponse {
    #[prost(string, tag = "1")]
    pub metric_code: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub limit: i64,
    #[prost(int64, tag = "3")]
    pub current_usage: i64,
    #[prost(int64, tag = "4")]
    pub remaining: i64,
    #[prost(double, tag = "5")]
    pub usage_percentage: f64,
    #[prost(enumeration = "QuotaPeriod", tag = "6")]
    pub period: i32,
    #[prost(message, optional, tag = "7")]
    pub period_start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub period_end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamEventsRequest {
    /// Organization to stream events for (required).
    #[prost(string, tag = "1")]
    pub organization_id: ::prost::alloc::string::String,
    /// Filter by event types (empty = all types).
    #[prost(enumeration = "UsageEventType", repeated, tag = "2")]
    pub event_types: ::prost::alloc::vec::Vec<i32>,
    /// Filter by metric codes (empty = all codes).
    #[prost(string, repeated, tag = "3")]
    pub metric_codes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Start streaming from this timestamp (optional).
    #[prost(message, optional, tag = "4")]
    pub since: ::core::option::Option<::prost_types::Timestamp>,
}
/// Types of usage events.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UsageEventType {
    Unspecified = 0,
    /// API Usage
    ApiCall = 1,
    LlmInference = 2,
    EmbeddingGeneration = 3,
    /// Token Usage
    InputTokens = 10,
    OutputTokens = 11,
    TotalTokens = 12,
    /// Compute Usage
    CpuMilliseconds = 20,
    MemoryMbSeconds = 21,
    GpuMilliseconds = 22,
    /// Storage Usage
    StorageBytes = 30,
    NetworkEgressBytes = 31,
    /// Enablement-Specific
    OversightRequest = 40,
    SandboxExecution = 41,
    MessageSent = 42,
}
impl UsageEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USAGE_EVENT_TYPE_UNSPECIFIED",
            Self::ApiCall => "API_CALL",
            Self::LlmInference => "LLM_INFERENCE",
            Self::EmbeddingGeneration => "EMBEDDING_GENERATION",
            Self::InputTokens => "INPUT_TOKENS",
            Self::OutputTokens => "OUTPUT_TOKENS",
            Self::TotalTokens => "TOTAL_TOKENS",
            Self::CpuMilliseconds => "CPU_MILLISECONDS",
            Self::MemoryMbSeconds => "MEMORY_MB_SECONDS",
            Self::GpuMilliseconds => "GPU_MILLISECONDS",
            Self::StorageBytes => "STORAGE_BYTES",
            Self::NetworkEgressBytes => "NETWORK_EGRESS_BYTES",
            Self::OversightRequest => "OVERSIGHT_REQUEST",
            Self::SandboxExecution => "SANDBOX_EXECUTION",
            Self::MessageSent => "MESSAGE_SENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USAGE_EVENT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "API_CALL" => Some(Self::ApiCall),
            "LLM_INFERENCE" => Some(Self::LlmInference),
            "EMBEDDING_GENERATION" => Some(Self::EmbeddingGeneration),
            "INPUT_TOKENS" => Some(Self::InputTokens),
            "OUTPUT_TOKENS" => Some(Self::OutputTokens),
            "TOTAL_TOKENS" => Some(Self::TotalTokens),
            "CPU_MILLISECONDS" => Some(Self::CpuMilliseconds),
            "MEMORY_MB_SECONDS" => Some(Self::MemoryMbSeconds),
            "GPU_MILLISECONDS" => Some(Self::GpuMilliseconds),
            "STORAGE_BYTES" => Some(Self::StorageBytes),
            "NETWORK_EGRESS_BYTES" => Some(Self::NetworkEgressBytes),
            "OVERSIGHT_REQUEST" => Some(Self::OversightRequest),
            "SANDBOX_EXECUTION" => Some(Self::SandboxExecution),
            "MESSAGE_SENT" => Some(Self::MessageSent),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IngestStatus {
    Unspecified = 0,
    Accepted = 1,
    Duplicate = 2,
    ValidationError = 3,
    QuotaExceeded = 4,
    InternalError = 5,
}
impl IngestStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "INGEST_STATUS_UNSPECIFIED",
            Self::Accepted => "INGEST_STATUS_ACCEPTED",
            Self::Duplicate => "INGEST_STATUS_DUPLICATE",
            Self::ValidationError => "INGEST_STATUS_VALIDATION_ERROR",
            Self::QuotaExceeded => "INGEST_STATUS_QUOTA_EXCEEDED",
            Self::InternalError => "INGEST_STATUS_INTERNAL_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INGEST_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "INGEST_STATUS_ACCEPTED" => Some(Self::Accepted),
            "INGEST_STATUS_DUPLICATE" => Some(Self::Duplicate),
            "INGEST_STATUS_VALIDATION_ERROR" => Some(Self::ValidationError),
            "INGEST_STATUS_QUOTA_EXCEEDED" => Some(Self::QuotaExceeded),
            "INGEST_STATUS_INTERNAL_ERROR" => Some(Self::InternalError),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QuotaPeriod {
    Unspecified = 0,
    Hourly = 1,
    Daily = 2,
    Weekly = 3,
    Monthly = 4,
    Lifetime = 5,
}
impl QuotaPeriod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "QUOTA_PERIOD_UNSPECIFIED",
            Self::Hourly => "QUOTA_PERIOD_HOURLY",
            Self::Daily => "QUOTA_PERIOD_DAILY",
            Self::Weekly => "QUOTA_PERIOD_WEEKLY",
            Self::Monthly => "QUOTA_PERIOD_MONTHLY",
            Self::Lifetime => "QUOTA_PERIOD_LIFETIME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "QUOTA_PERIOD_UNSPECIFIED" => Some(Self::Unspecified),
            "QUOTA_PERIOD_HOURLY" => Some(Self::Hourly),
            "QUOTA_PERIOD_DAILY" => Some(Self::Daily),
            "QUOTA_PERIOD_WEEKLY" => Some(Self::Weekly),
            "QUOTA_PERIOD_MONTHLY" => Some(Self::Monthly),
            "QUOTA_PERIOD_LIFETIME" => Some(Self::Lifetime),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod metering_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// MeteringService handles usage event ingestion and quota checks.
    #[derive(Debug, Clone)]
    pub struct MeteringServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MeteringServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MeteringServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MeteringServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MeteringServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Ingest a single usage event.
        pub async fn ingest_event(
            &mut self,
            request: impl tonic::IntoRequest<super::IngestEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestEventResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/creto.metering.v1.MeteringService/IngestEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("creto.metering.v1.MeteringService", "IngestEvent"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Ingest multiple usage events in a batch.
        pub async fn ingest_event_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::IngestEventBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestEventBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/creto.metering.v1.MeteringService/IngestEventBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "creto.metering.v1.MeteringService",
                        "IngestEventBatch",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Check if a quota allows a specific usage.
        pub async fn check_quota(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckQuotaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckQuotaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/creto.metering.v1.MeteringService/CheckQuota",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("creto.metering.v1.MeteringService", "CheckQuota"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get current quota status for a metric.
        pub async fn get_quota_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetQuotaStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetQuotaStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/creto.metering.v1.MeteringService/GetQuotaStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "creto.metering.v1.MeteringService",
                        "GetQuotaStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream events for real-time processing (admin only).
        pub async fn stream_events(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::UsageEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/creto.metering.v1.MeteringService/StreamEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("creto.metering.v1.MeteringService", "StreamEvents"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod metering_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MeteringServiceServer.
    #[async_trait]
    pub trait MeteringService: std::marker::Send + std::marker::Sync + 'static {
        /// Ingest a single usage event.
        async fn ingest_event(
            &self,
            request: tonic::Request<super::IngestEventRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestEventResponse>,
            tonic::Status,
        >;
        /// Ingest multiple usage events in a batch.
        async fn ingest_event_batch(
            &self,
            request: tonic::Request<super::IngestEventBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IngestEventBatchResponse>,
            tonic::Status,
        >;
        /// Check if a quota allows a specific usage.
        async fn check_quota(
            &self,
            request: tonic::Request<super::CheckQuotaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckQuotaResponse>,
            tonic::Status,
        >;
        /// Get current quota status for a metric.
        async fn get_quota_status(
            &self,
            request: tonic::Request<super::GetQuotaStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetQuotaStatusResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamEvents method.
        type StreamEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::UsageEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream events for real-time processing (admin only).
        async fn stream_events(
            &self,
            request: tonic::Request<super::StreamEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamEventsStream>,
            tonic::Status,
        >;
    }
    /// MeteringService handles usage event ingestion and quota checks.
    #[derive(Debug)]
    pub struct MeteringServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MeteringServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MeteringServiceServer<T>
    where
        T: MeteringService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/creto.metering.v1.MeteringService/IngestEvent" => {
                    #[allow(non_camel_case_types)]
                    struct IngestEventSvc<T: MeteringService>(pub Arc<T>);
                    impl<
                        T: MeteringService,
                    > tonic::server::UnaryService<super::IngestEventRequest>
                    for IngestEventSvc<T> {
                        type Response = super::IngestEventResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IngestEventRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MeteringService>::ingest_event(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IngestEventSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/creto.metering.v1.MeteringService/IngestEventBatch" => {
                    #[allow(non_camel_case_types)]
                    struct IngestEventBatchSvc<T: MeteringService>(pub Arc<T>);
                    impl<
                        T: MeteringService,
                    > tonic::server::UnaryService<super::IngestEventBatchRequest>
                    for IngestEventBatchSvc<T> {
                        type Response = super::IngestEventBatchResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IngestEventBatchRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MeteringService>::ingest_event_batch(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IngestEventBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/creto.metering.v1.MeteringService/CheckQuota" => {
                    #[allow(non_camel_case_types)]
                    struct CheckQuotaSvc<T: MeteringService>(pub Arc<T>);
                    impl<
                        T: MeteringService,
                    > tonic::server::UnaryService<super::CheckQuotaRequest>
                    for CheckQuotaSvc<T> {
                        type Response = super::CheckQuotaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CheckQuotaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MeteringService>::check_quota(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CheckQuotaSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/creto.metering.v1.MeteringService/GetQuotaStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetQuotaStatusSvc<T: MeteringService>(pub Arc<T>);
                    impl<
                        T: MeteringService,
                    > tonic::server::UnaryService<super::GetQuotaStatusRequest>
                    for GetQuotaStatusSvc<T> {
                        type Response = super::GetQuotaStatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetQuotaStatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MeteringService>::get_quota_status(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetQuotaStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/creto.metering.v1.MeteringService/StreamEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamEventsSvc<T: MeteringService>(pub Arc<T>);
                    impl<
                        T: MeteringService,
                    > tonic::server::ServerStreamingService<super::StreamEventsRequest>
                    for StreamEventsSvc<T> {
                        type Response = super::UsageEvent;
                        type ResponseStream = T::StreamEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamEventsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MeteringService>::stream_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MeteringServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "creto.metering.v1.MeteringService";
    impl<T> tonic::server::NamedService for MeteringServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
